---
title: "AXYS correlations: Imputation"
author: "Angela Ching"
date: "`r Sys.Date()`"
output: 
  html_notebook:
    toc: yes
---

# Packages

```{r}
library(tidyverse)
library(readxl)
library(ggplot2)

# For missing value imputation
library(mice)         # for imputing missing values
library(VIM)
library(lattice)
```

# Load AXYS data

```{r}
# load chemical list
chem_list <- read_csv("../../data/2022-10-18_AXYS_chemicals_list_AC.csv") %>%
  dplyr::select(Compound, Dioxin_subtype)

# load AXYS data
axys_pops <- read_csv("../../outputs/2024-08-24_ProjectGrant_excluded_outliers_for_single_analyte_analyses.csv") %>%
  dplyr::select(-c(CONC_BLANK_adj, IS_BLANK_ADJ_CONC_HIGHER_THAN_LOD)) %>%
  mutate(BLANK_and_LOD_adj = as.numeric(BLANK_and_LOD_adj),
         File = factor(File),
         COMPOUND = case_when(str_detect(COMPOUND, "TOTAL") ~ str_to_sentence(COMPOUND),
                              str_detect(COMPOUND, " Epoxide") ~ str_to_sentence(COMPOUND),
                              TRUE ~ COMPOUND),
         across(where(is.character), str_squish))

axys_pops_2 <- axys_pops %>%
  dplyr::select(-c(File, LAB_FLAG, DETECTION_LIMIT)) %>%
  mutate(across(where(is.character), str_squish))


```
```{r}
subset_tissue <- function(tissue) {
  axys_pops_2 %>%
    dplyr::filter(!str_detect(COMPOUND, "Total"), TISSUE_TYPE == tissue) %>%
    dplyr::select(DONOR, COMPOUND, BLANK_and_LOD_adj) %>%
    group_by(DONOR) %>%
    pivot_wider(names_from = COMPOUND, values_from = BLANK_and_LOD_adj) %>%
    ungroup()
}

axys_pops_panc <- subset_tissue("Pancreas")
axys_pops_adip <- subset_tissue("Adipose")
```

# Impute missing values

```{r, fig.width = 10}
# Create a list for each pollutant class
get_compound_list <- function(type, tissue) {
  axys_pops_2 %>%
    dplyr::filter(Type == type, TISSUE_TYPE == tissue) %>%
    dplyr::select(COMPOUND) %>%
    distinct(COMPOUND) %>%
    pull(COMPOUND)
}

# Generate compound lists
dioxin_list_panc <- get_compound_list("Dioxin", "Pancreas")
ocp_list_panc <- get_compound_list("OCP", "Pancreas")
pcb_list_adip <- get_compound_list("PCB", "Adipose")
ocp_list_adip <- get_compound_list("OCP", "Adipose")

# Select data for imputation
panc_dioxin_impute <- axys_pops_panc[, dioxin_list_panc]
panc_ocp_impute <- axys_pops_panc[, ocp_list_panc]

adip_pcb_impute <- axys_pops_adip[, pcb_list_adip]
adip_ocp_impute <- axys_pops_adip[, ocp_list_adip]

# Plot missingness pattern
md.pattern(panc_dioxin_impute, rotate.names = TRUE)
md.pattern(panc_ocp_impute, rotate.names = TRUE)

md.pattern(adip_pcb_impute, rotate.names = TRUE)
md.pattern(adip_ocp_impute, rotate.names = TRUE)

# Plot the missing values
axys_panc_dioxin_miss = aggr(panc_dioxin_impute, numbers=TRUE, sortVars=TRUE, labels=names(axys_pops_panc), col = mdc(1:6), cex.axis=.7, gap=3, ylab=c("Proportion of missingness in pancreas dioxins","Missingness Pattern"))

axys_panc_ocp_miss = aggr(panc_ocp_impute, numbers=TRUE, sortVars=TRUE, labels=names(axys_pops_panc), col = mdc(1:6), cex.axis=.7, gap=3, ylab=c("Proportion of missingness in pancreas OCPs","Missingness Pattern"))

axys_adip_pcb_miss = aggr(adip_pcb_impute, numbers=TRUE, sortVars=TRUE, labels=names(axys_pops_adip), col = mdc(1:6), cex.axis=.7, gap=3, ylab=c("Proportion of missingness in adipose PCBs","Missingness Pattern"))

axys_adip_ocp_miss = aggr(adip_ocp_impute, numbers=TRUE, sortVars=TRUE, labels=names(axys_pops_adip), col = mdc(1:6), cex.axis=.7, gap=3, ylab=c("Proportion of missingness in adipose OCPs","Missingness Pattern"))

#Drawing margin plot
marginplot(panc_ocp_impute[, c("Dieldrin", "HCH, beta")], col = mdc(1:2), cex.numbers = 1.2, pch = 19)
marginplot(panc_ocp_impute[, c("HCH, beta", "Heptachlor epoxide")], col = mdc(1:2), cex.numbers = 1.2, pch = 19)

marginplot(adip_pcb_impute[, c("PCB 118", "PCB 155")], col = mdc(1:2), cex.numbers = 1.2, pch = 19)
marginplot(adip_ocp_impute[, c("Dieldrin", "HCH, beta")], col = mdc(1:2), cex.numbers = 1.2, pch = 19)
marginplot(adip_ocp_impute[, c("HCH, beta", "Heptachlor epoxide")], col = mdc(1:2), cex.numbers = 1.2, pch = 19)
```

```{r, fig.width = 20}
#Imputing missing values using mice

# Make all column names syntactically valid in R
# colnames(panc_dioxin_impute) <- make.names(colnames(panc_dioxin_impute), unique = TRUE)
# colnames(panc_ocp_impute) <- make.names(colnames(panc_ocp_impute), unique = TRUE)
# 
# colnames(adip_pcb_impute) <- make.names(colnames(adip_pcb_impute), unique = TRUE)
# colnames(adip_ocp_impute) <- make.names(colnames(adip_ocp_impute), unique = TRUE)

# Run the mice imputation
# mice_impute_panc_dioxin <- mice(panc_dioxin_impute, m = 5, maxit = 40)
# mice_impute_panc_ocp <- mice(panc_ocp_impute, m = 5, maxit = 40)
# 
# mice_impute_adip_pcb <- mice(adip_pcb_impute, m = 5, maxit = 40)
# mice_impute_adip_ocp <- mice(adip_ocp_impute, m = 5, maxit = 40)

#Imputed dataset
# imputed_data_panc_dioxin = mice::complete(mice_impute_panc_dioxin, 5)
# imputed_data_panc_ocp <- mice::complete(mice_impute_panc_ocp, 5)
# 
# imputed_data_adip_pcb = mice::complete(mice_impute_adip_pcb, 5)
# imputed_data_adip_ocp = mice::complete(mice_impute_adip_ocp, 5)

# write_csv(imputed_data_panc_dioxin, "2024-09-03_imputed_pancreas_dioxin_data.csv")
# write_csv(imputed_data_panc_ocp, "2024-09-03_imputed_pancreas_ocp_data.csv")
# write_csv(imputed_data_adip_pcb, "2024-09-03_imputed_adipose_pcb_data.csv")
# write_csv(imputed_data_adip_ocp, "2024-09-03_imputed_adipose_ocp_data.csv")

#Plotting and comparing values with xyplot()
# xyplot(mice_impute_panc_ocp, Dieldrin ~ Heptachlor.epoxide | .imp, pch = 20, cex = 1.4)
# xyplot(mice_impute_adip_pcb, PCB.118 ~ PCB.155 | .imp, pch = 20, cex = 1.4)
```

# Session Info

```{r}
sessionInfo()
```